// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 10000m,
                            Description = "Fast food sotib olishga",
                            ExpenseCategoryId = 1,
                            ExpenseDate = new DateTime(2024, 10, 31, 20, 38, 45, 978, DateTimeKind.Utc).AddTicks(8970)
                        },
                        new
                        {
                            Id = 2,
                            Cost = 5000m,
                            Description = "Metroda chipta sotib olish",
                            ExpenseCategoryId = 2,
                            ExpenseDate = new DateTime(2024, 10, 31, 20, 38, 45, 978, DateTimeKind.Utc).AddTicks(9030)
                        },
                        new
                        {
                            Id = 3,
                            Cost = 1000m,
                            Description = "Telegram uchun to'lov",
                            ExpenseCategoryId = 3,
                            ExpenseDate = new DateTime(2024, 10, 31, 20, 38, 45, 978, DateTimeKind.Utc).AddTicks(9040)
                        },
                        new
                        {
                            Id = 4,
                            Cost = 2000m,
                            Description = "PUBG o'ynash uchun",
                            ExpenseCategoryId = 4,
                            ExpenseDate = new DateTime(2024, 10, 31, 20, 38, 45, 978, DateTimeKind.Utc).AddTicks(9040)
                        },
                        new
                        {
                            Id = 5,
                            Cost = 1000m,
                            Description = "Konsertga bilet sotib olish",
                            ExpenseCategoryId = 5,
                            ExpenseDate = new DateTime(2024, 10, 31, 20, 38, 45, 978, DateTimeKind.Utc).AddTicks(9050)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oziq-ovqat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mobil aloqa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Internet"
                        },
                        new
                        {
                            Id = 5,
                            Name = "O'yin-kulgi"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Expense", b =>
                {
                    b.HasOne("Domain.Entities.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("Domain.Entities.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
